### ISSUE TITLE
환경변수 ADT 수정사항

### ISSUE THREAD

**Issue by gemstoneyang** [mingxoxo/minishell#11]
**1. set_key_value 함수**
- 반환값을 true/false로 해야할까?
- 이미 해당 key를 가진 함수가 있을 경우 기존 value를 free로 해제하는데, value가 free할 필요가 없다면?

**2. clear_enode 함수**
- key, value를 해제할 함수를 지정할 수 있는데, key와 value가 할당된 방식이 다르다면?

**3. 어떻게 사용될 것인가**
- 모든 key, value를 매번 할당해 사용될까? 아니면 "name" 과 같이 const한 값이 사용될 것인가?

**4.  search_key_enode 함수**
- enode 구조체 반환이 아니라 문자열을 반환하면 사용하기 더 편할 것 같다

**5. envp에서 환경변수 가져오는 함수 추가**

**6. del_key_enode 함수**
- 삭제할 환경변수가 없을 시 에러 메시지를 띄우지 말고 그냥 무시
- 삭제가 됐는지 int로 반환

검토 부탁드려용 😯

**Comment by mingxoxo** [comment]
- export할 때 무조건 처음에 나오는 = 를 기준으로 [key]=[value]가 나누어짐
- 따옴표 처리는 다른 함수와 함께 진행해야 함

### ✅ main.c 작성 방법 예시
```
#include "includes/ds_envp.h"

static void	print_envp(t_envp *envp)
{
	t_enode	*node;

	printf("--------------------------\n");
	printf("envp cnt: %d\n", envp->cnt);
	node = envp->head;
	while (node)
	{
		printf("%s = %s\n", node->key, node->value);
		node = node->next;
	}
	printf("--------------------------\n");
}

static void	print_node(t_enode *node)
{
	if (!node)
	{
		printf("%p\n", node);
		return ;
	}
	printf("%s = %s\n", node->key, node->value);
}

int	main(int argc, char **argv, char **envp)
{
	t_envp  my_envp;

	init_envp(&my_envp, envp);
	print_envp(&my_envp);
	cast_envp_line(&my_envp, "wonyang=babo");
	print_envp(&my_envp);
	cast_envp_line(&my_envp, "wonyang=realbabo");
	print_envp(&my_envp);
    clear_enode(&my_envp);
    print_envp(&my_envp);
    return (0);
}
```

**Comment by mingxoxo** [comment]
## 👩🏻‍💻 변경사항

1. `set_key_value` 함수

반환값을 `t_error`로 설정

2. `key`, `value` 메모리 해제

무조건 `key`, `value`는 `malloc`으로 할당되어 들어온다고 가정
따라서 `free` 함수를 통해 메모리가 해제되도록 모두 변경
+ del_key, del_value leak 해결

3. `search_key_value` 함수 추가

`key`에 해당하는 `value`를 반환
찾지 못할 시 `NULL` 반환

4. `envp`에서 환경변수 가져오는 함수 추가

`init_envp` 함수에서 `cast_envp_list(envp, arr)` 와 `cast_envp_arr(envp)`를 실행하도록 작성됨

5. `del_key_enode` 함수

삭제할 환경변수가 없을 시 에러 메시지를 띄우지 말고 그냥 무시
반환 값 `int`로 수정

6. `envp` 구조체 수정 및 `refresh_arr`함수 작성

명령 `env`가 실행될 경우, execve에서 인자로 쓰이는 경우 등을 위해 `cast_envp_arr` 함수를 통해 만든 arr(main에서 받는 char **envp 형태)를 저장해서 가지고 다닌다.
만약 export, unset과 같은 명령어로 enode list가 수정될 시 `refresh_arr`함수를 통해 `arr`을 해제하고 다시 생성한다.

```
typedef struct s_envp
{
	struct s_enode	*head;
	int				cnt;
	char			**arr;
}					t_envp;
```

7. `clear_enode` -> `clear_envp` 함수로 변경

envp에 대해 할당한 힙 메모리 전부 해제(`enode list`, `arr`)
