### ISSUE TITLE
ds_envp 적용 오류

### ISSUE THREAD

**Issue by gemstoneyang** [mingxoxo/minishell#21]
## 🚅 Issue 한 줄 요약

ds_envp 라이브러리가 동작을 제대로 안합니다..

## 🤷 Issue 세부 내용

1. refresh_arr 함수에서 envp->arr 가 널일때 free해서 세그폴트가 떠요
2. OLDPWD 값을 제대로 가져오지 않습니다.

## ✨ 기대 결과

잘 동작하면 좋겠어요!

## 📸 스크린샷
오류난 메인함수입니다 !

```
int	main(int c, char **a, char **m)
{
	t_envp envp;

	init_envp(&envp, m);
	ft_cd(a, &envp);
	printf("PWD : %s\n", search_key_value(&envp, "PWD"));
	printf("OLDPWD : %s\n", search_key_value(&envp, "OLDPWD"));
	return (0);
}
```

**Comment by mingxoxo** [comment]
https://github.com/mingxoxo/minishell/pull/24
해결 완료
